### ISSUE TITLE
tensorflow.python.framework.errors_impl.UnknownError: Fail to find the dnn implementation.

### ISSUE THREAD

**Issue by shamoons** [minimaxir/textgenrnn#133]
Output is:
```
1,016,957 texts collected.
Training new model w/ 2-layer, 128-cell LSTMs
Training on 39,616,040 character sequences.
Epoch 1/1
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    new_model=True, header=False)
  File "/home1/ss19015/.local/share/virtualenvs/PyOctoscraper-KIv7syK9/lib/python3.6/site-packages/textgenrnn/textgenrnn.py", line 327, in train_from_file
    texts, context_labels=context_labels, **kwargs)
  File "/home1/ss19015/.local/share/virtualenvs/PyOctoscraper-KIv7syK9/lib/python3.6/site-packages/textgenrnn/textgenrnn.py", line 298, in train_new_model
    **kwargs)
  File "/home1/ss19015/.local/share/virtualenvs/PyOctoscraper-KIv7syK9/lib/python3.6/site-packages/textgenrnn/textgenrnn.py", line 224, in train_on_texts
    validation_steps=val_steps
  File "/home1/ss19015/.local/share/virtualenvs/PyOctoscraper-KIv7syK9/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home1/ss19015/.local/share/virtualenvs/PyOctoscraper-KIv7syK9/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home1/ss19015/.local/share/virtualenvs/PyOctoscraper-KIv7syK9/lib/python3.6/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/home1/ss19015/.local/share/virtualenvs/PyOctoscraper-KIv7syK9/lib/python3.6/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/home1/ss19015/.local/share/virtualenvs/PyOctoscraper-KIv7syK9/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home1/ss19015/.local/share/virtualenvs/PyOctoscraper-KIv7syK9/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home1/ss19015/.local/share/virtualenvs/PyOctoscraper-KIv7syK9/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home1/ss19015/.local/share/virtualenvs/PyOctoscraper-KIv7syK9/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Fail to find the dnn implementation.
	 [[{{node rnn_1_1/CudnnRNN}}]]
```

My code is:
```
from tensorflow.python.client import device_lib
from textgenrnn import textgenrnn
print(device_lib.list_local_devices())

textgen = textgenrnn()
textgen.train_from_file('data/small.txt', num_epochs=5, word_level=True, rnn_bidirectional=True,
                        new_model=True, header=False)
textgen.generate(interactive=True, top_n=5)
```

**Comment by AHFriedman** [comment]
I'm having the same issue. I was wondering if you found a solution?

**Comment by sarah-tran** [comment]
see #81. what worked for me was creating a fresh conda env:
`conda create -n myenv`
`conda install tensorflow keras`

**Comment by graynk** [comment]
You can do either
`textgen = textgenrnn(allow_growth=True)` (though it doesn't work with tensorflow 2)
or
```
import tensorflow as tf
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], enable=True)
```

**Comment by michellemboya** [comment]
I'm having the same issue - I tried the solutions above but none worked. Do you know what this could be?
