### ISSUE TITLE
Can import modules

### ISSUE THREAD

**Issue by test1230-lab** [minimaxir/textgenrnn#191]
>>from textgenrnn import textgenrnn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\textgenrnn\__init__.py", line 1, in <module>
    from .textgenrnn import textgenrnn
  File "C:\Users\wow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\textgenrnn\textgenrnn.py", line 1, in <module>
    from tensorflow.keras.callbacks import LearningRateScheduler, Callback
  File "C:\Users\wow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tensorflow\__init__.py", line 295, in <module>
    from tensorflow.python.ops.math_ops import linspace_nd as linspace
ImportError: cannot import name 'linspace_nd' from 'tensorflow.python.ops.math_ops' (C:\Users\wow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tensorflow\python\ops\math_ops.py)

after i installed cuda and cuDNN and edited some paths. sorry for the questions
i installed these because it wasnt using gpu to train
gtx 1070
https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html https://www.tensorflow.org/install/gpu were followed for windows 10
it might be the path thing
 sorry  if this is a dumb question :)

**Comment by test1230-lab** [comment]
i fixed with a uninstall and reinstall
now i have this error
https://pastebin.com/dvvgHgTy
