### ISSUE TITLE
Permission denied error while training on data

### ISSUE THREAD

**Issue by Gongxter** [minimaxir/textgenrnn#194]
I simply try to train the model like this on Windows 10:
```
textgen = textgenrnn()
textgen.train_on_texts(text,num_epochs=1)
```

then it starts to train:

```
Training on 3,904 character sequences.
30/30 [==============================] - ETA: 0s - loss: 1.2120####################
Temperature: 0.2
####################
..
```

and crashes, at what i guess is the end of an epoch when the weights are tried to be saved, with this error:

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Unistuff\raspiProject\audio\audioGenerator.py", line 25, in <module>
    textgen.train_on_texts(text,num_epochs=1)
  File "C:\Users\Timm7\AppData\Roaming\Python\Python37\site-packages\textgenrnn\textgenrnn.py", line 271, in train_on_texts
    validation_steps=val_steps
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 876, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\keras\callbacks.py", line 365, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Users\Timm7\AppData\Roaming\Python\Python37\site-packages\textgenrnn\utils.py", line 309, in on_epoch_end
    "{}_weights.hdf5".format(self.weights_name))
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1150, in save_weights
    with h5py.File(filepath, 'w') as f:
  File "C:\Program Files\Python37\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "C:\Program Files\Python37\lib\site-packages\h5py\_hl\files.py", line 179, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'textgenrnn_weights.hdf5', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302)
```

Eventually after each epoch the weights get saved and in this case (I don't know if it is windows specific) are tried to be saved in a file which has no path.
Am i doing something wrong or do I miss something?.

**Comment by Gongxter** [comment]
Okay this problem happened because my IDE PyCharm had no administrator rights. After executing the script via WSL2 and powersehll and both worked, I started PyCharm as administrator and everything worked fine.
