### ISSUE TITLE
Can't even load it, Module not found?

### ISSUE THREAD

**Issue by WabMiran** [minimaxir/textgenrnn#202]
I keep getting this error code every time i try to open the most basic py file, that simply has "from textgenrnn import textgenrnn and textgen = textgenrnn()". I installed everything using PIP

`2020-07-17 01:14:10.368901: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "C:\Users\Miran\Desktop\yes.py", line 1, in <module>
    from textgenrnn import textgenrnn
  File "C:\Users\Miran\AppData\Local\Programs\Python\Python38\lib\site-packages\textgenrnn\__init__.py", line 1, in <module>
    from .textgenrnn import textgenrnn
  File "C:\Users\Miran\AppData\Local\Programs\Python\Python38\lib\site-packages\textgenrnn\textgenrnn.py", line 14, in <module>
    from keras.backend.tensorflow_backend import set_session
ModuleNotFoundError: No module named 'keras.backend.tensorflow_backend'; 'keras.backend' is not a package`

**Comment by WabMiran** [comment]
Found the fix! You need to manually download Keras version 2.4.0 and not the latest version for textgenrnn to work! 
"pip install keras==2.4.0" for anyone who needs it
