### ISSUE TITLE
Failed to call ThenRnnForward

### ISSUE THREAD

**Issue by 512DuncanL** [minimaxir/textgenrnn#255]
I get this error when I try to train a model with gpu:
```
C:\Users\duncan\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\optimizer_v2\adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)
2022-04-12 18:49:37.817181: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-12 18:49:38.242032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1251 MB memory:  -> device: 0, name: NVIDIA GeForce MX450, pci bus id: 0000:2b:00.0, compute capability: 7.5
Training new model w/ 4-layer, 512-cell LSTMs
Training on 559,108 character sequences.
Epoch 1/50
2022-04-12 18:49:44.081802: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8303
2022-04-12 18:49:44.216000: E tensorflow/stream_executor/dnn.cc:868] CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/stream_executor/cuda/cuda_dnn.cc(2032): 'cudnnRNNForwardTraining( cudnn.handle(), rnn_desc.handle(), model_dims.max_seq_length, input_desc.handles(), input_data.opaque(), input_h_desc.handle(), input_h_data.opaque(), input_c_desc.handle(), input_c_data.opaque(), rnn_desc.params_handle(), params.opaque(), output_desc.handles(), output_data->opaque(), output_h_desc.handle(), output_h_data->opaque(), output_c_desc.handle(), output_c_data->opaque(), workspace.opaque(), workspace.size(), reserve_space.opaque(), reserve_space.size())'
2022-04-12 18:49:44.216389: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at cudnn_rnn_ops.cc:1563 : INTERNAL: Failed to call ThenRnnForward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 100, 512, 1, 40, 256, 512]
Traceback (most recent call last):
  File "C:\Users\duncan\OneDrive - EiM\Desktop\train text.py", line 30, in <module>
    train_function(
  File "C:\Users\duncan\AppData\Local\Programs\Python\Python38\lib\site-packages\textgenrnn\textgenrnn.py", line 374, in train_from_largetext_file
    self.train_new_model(
  File "C:\Users\duncan\AppData\Local\Programs\Python\Python38\lib\site-packages\textgenrnn\textgenrnn.py", line 325, in train_new_model
    self.train_on_texts(texts, new_model=True,
  File "C:\Users\duncan\AppData\Local\Programs\Python\Python38\lib\site-packages\textgenrnn\textgenrnn.py", line 257, in train_on_texts
    model_t.fit(gen, steps_per_epoch=steps_per_epoch,
  File "C:\Users\duncan\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\duncan\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError: Graph execution error:

Failed to call ThenRnnForward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 100, 512, 1, 40, 256, 512]
         [[{{node CudnnRNN}}]]
         [[model_1/rnn_1/PartitionedCall]] [Op:__inference_train_function_11834]
2022-04-12 18:49:44.287052: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: FAILED_PRECONDITION: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]
```
Changing training parameters does not seem to help, and task manager shows that the gpu isn't running out of memory

**Comment by 512DuncanL** [comment]
Fixed by installing the newest cudnn update
