### ISSUE TITLE
Can't install on Linux

### ISSUE THREAD

**Issue by MaraJadeLives** [minimaxir/textgenrnn#270]
Here's the last bit of the install code. I'm not great with the command line, but need some help with it. Can you please help? It's something about adding things to path.

Successfully built textgenrnn
Installing collected packages: tensorboard-plugin-wit, pyasn1, libclang, flatbuffers, wrapt, typing-extensions, tqdm, threadpoolctl, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, scipy, rsa, requests-oauthlib, pyasn1-modules, packaging, opt-einsum, MarkupSafe, markdown, keras, joblib, h5py, grpcio, google-pasta, gast, cachetools, astunparse, absl-py, werkzeug, scikit-learn, google-auth, google-auth-oauthlib, tensorboard, tensorflow, textgenrnn
  WARNING: The script tqdm is installed in '/home/alexandra/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts pyrsa-decrypt, pyrsa-encrypt, pyrsa-keygen, pyrsa-priv2pub, pyrsa-sign and pyrsa-verify are installed in '/home/alexandra/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script markdown_py is installed in '/home/alexandra/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script google-oauthlib-tool is installed in '/home/alexandra/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tensorboard is installed in '/home/alexandra/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts estimator_ckpt_converter, import_pb_to_tensorboard, saved_model_cli, tensorboard, tf_upgrade_v2, tflite_convert, toco and toco_from_protos are installed in '/home/alexandra/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed MarkupSafe-2.1.2 absl-py-1.4.0 astunparse-1.6.3 cachetools-5.3.0 flatbuffers-23.3.3 gast-0.4.0 google-auth-2.16.2 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 grpcio-1.51.3 h5py-3.8.0 joblib-1.2.0 keras-2.11.0 libclang-15.0.6.1 markdown-3.4.1 opt-einsum-3.3.0 packaging-23.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-oauthlib-1.3.1 rsa-4.9 scikit-learn-1.2.2 scipy-1.10.1 tensorboard-2.11.2 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 tensorflow-2.11.0 tensorflow-estimator-2.11.0 tensorflow-io-gcs-filesystem-0.31.0 termcolor-2.2.0 textgenrnn-2.0.0 threadpoolctl-3.1.0 tqdm-4.65.0 typing-extensions-4.5.0 werkzeug-2.2.3 wrapt-1.15.0
alexandra@Fun:~$ python
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3
alexandra@Fun:~$ python3
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from textgenrnn import textgenrnn
2023-03-18 05:52:44.699635: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-03-18 05:52:44.699676: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-03-18 05:52:47.214840: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-03-18 05:52:47.214951: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-03-18 05:52:47.214967: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alexandra/.local/lib/python3.10/site-packages/textgenrnn/__init__.py", line 1, in <module>
    from .textgenrnn import textgenrnn
  File "/home/alexandra/.local/lib/python3.10/site-packages/textgenrnn/textgenrnn.py", line 5, in <module>
    from tensorflow.keras.utils import multi_gpu_model
ImportError: cannot import name 'multi_gpu_model' from 'tensorflow.keras.utils' (/home/alexandra/.local/lib/python3.10/site-packages/keras/api/_v2/keras/utils/__init__.py)
>>> textgernn = textgernn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'textgernn' is not defined
>>> textgernn = textgernn()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'textgernn' is not defined
>>>

**Comment by renning1205** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，邮件已收到，尽快回复。

**Comment by MaraJadeLives** [comment]
As it turned out, I think I might have fixed it. I realized I mistyped some
stuff, and also added something to $PATH.
