### ISSUE TITLE
ValueError: Layer #1 (named "embedding")

### ISSUE THREAD

**Issue by ihavetoomanyquestions** [minimaxir/textgenrnn#31]
Hi,

After I train the model with the following config: 

num_epochs: 1000
gen_epochs: 10
batch_size: 128
prop_keep: 1.0
new_model: True
model_config:
  rnn_layers: 2
  rnn_size: 128
  rnn_bidirectional: False
  max_length: 40
  dim_embeddings: 100
  word_level: False

I am trying to generate some text with the following code;

from textgenrnn import textgenrnn
textgen_2 = textgenrnn('weights.hdf5')
textgen_2.generate(3, temperature=1.0)

But every time I get the following error: (i changed the dataset, the number of epochs, trained a few times from scratch, result is the same...)

Traceback (most recent call last):
  File "test.py", line 2, in <module>
    textgen_2 = textgenrnn('weights.hdf5')
  File "textgenrnn/textgenrnn.py", line 66, in __init__
    weights_path=weights_path)
  File "textgenrnn/model.py", line 38, in textgenrnn_model
    model.load_weights(weights_path, by_name=True)
  File "lib/python3.6/site-packages/keras/engine/network.py", line 1177, in load_weights
    reshape=reshape)
  File "lib/python3.6/site-packages/keras/engine/saving.py", line 1018, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #1 (named "embedding"), weight <tf.Variable 'embedding/embeddings:0' shape=(465, 100) dtype=float32_ref> has shape (465, 100), but the saved weight has shape (91, 100).

What might be the problem?

**Comment by ihavetoomanyquestions** [comment]
Sorry for spamming, the problem was fixed after I initialized the model like that (with vocab & config files):

textgen = textgenrnn(weights_path='weights.hdf5',
                       vocab_path='vocab.json',
                       config_path='config.json')

on the other hand, it would be nice to put to the readme about how to load your own models, because i was a bit confused by the following example in the readme (where I got the impression that just hdf5 file was enough to init the model): 

textgen_2 = textgenrnn('/weights/hacker_news.hdf5')
textgen_2.generate(3, temperature=1.0)
