### ISSUE TITLE
Unable to open largetext weights.

### ISSUE THREAD

**Issue by janelleshane** [minimaxir/textgenrnn#56]
I successfully trained a model using train_from_largetext and saved the weights as 'weights/recipes.hdf5'.

However, I don't seem to be able to reopen the saved weights. When I try:

recipes.save('weights/recipes.hdf5')
recipes2 = textgenrnn('weights/recipes.hdf5')

I get the following error message when I try to reopen the weights:

> >>> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/janelle_shane/textgenrnn/textgenrnn/textgenrnn.py", line 65, in __init__
>     weights_path=weights_path)
>   File "/home/janelle_shane/textgenrnn/textgenrnn/model.py", line 38, in textgenrnn_model
>     model.load_weights(weights_path, by_name=True)
>   File "/home/janelle_shane/.pyenv/versions/3.5.5/lib/python3.5/site-packages/keras/engine/network.py", line 1177, in load_weights
>     reshape=reshape)
>   File "/home/janelle_shane/.pyenv/versions/3.5.5/lib/python3.5/site-packages/keras/engine/saving.py", line 1018, in load_weights_from_hdf5_group_by_name
>     str(weight_values[i].shape) + '.')
> ValueError: Layer #1 (named "embedding"), weight <tf.Variable 'embedding_8/embeddings:0' shape=(465, 100) dtype=float32_ref> has shape (465, 100), but the saved weight has shape (106, 100).
> 

This combo of commands works for models trained with regular train_from_file, so I wonder if there's some problem with train_from_largetext_file?

**Comment by minimaxir** [comment]
If you are using a custom model, you need to load with the `config.json` and the `vocab.json` that were also generated.

**Comment by janelleshane** [comment]
When I saved my model, it looks like it only saved a .hdf5 file, not the .json files. The command I used was something like this:
>>> recipes_old.save('weights/recipes.hdf5')

Then when I do this, after having trained some other models in the meantime:
>>> recipes = textgenrnn(weights_path='weights/recipes.hdf5', vocab_path='textgenrnn_vocab.json', config_path='textgenrnn_config
.json')

I don't get an error message, but the generated text looks like garbage.
>>> recipes.generate()
)    o  D  T wT f 99  95 u5555555555" "5''80g00'..t'' '-w...ssr0r0Bswoc3c- - 9- ""T0 0A5 p5-5F9G 5T '.'qr0   l -   0        00     J - 0      -  0       5 0      -  0         0      -  0         0      -            0      F        C                 - 6                 F                   -          

Was I supposed to save using a different method?

**Comment by minimaxir** [comment]
The `the saved weight has shape (106, 100).` part of the error message implies that a new model was trained (the `106` corresponds to the size of the vocabulary). Those files should have been generated before the model started training.

Each training epoch saves the weights; there shouldn't be a reason to explicitly call `.save()` and I should probably consider depreciating that.

I double checked the code path of `train_from_file` and this order-of-operations *should* be working correctly, although I'm not sure why garbage got generated.

**Comment by janelleshane** [comment]
When I ran the example above and got garbage, I had trained another model in the meantime, which presumably overwrote textgenrnn_vocab.json and textgenrnn_config.json. I guess the .save() strategy always worked for regular shorttext training b/c _vocab.json and _config.json weren't changing. Probably if I went back and tried to load a shorttext model after training a longtext model, it wouldn't work either.

**Solution:** if I want to save a largetext model to come back to later, it looks like the strategy is to manually copy textgenrnn_weights.hdf5, textgenrnn_vocab.json and textgenrnn_config.json to a new folder before running another model.

I confirmed that this works by training a largetext model:
`recipes_len20.train_from_largetext_file('datasets/recipes.txt', new_model=True, num_epochs=1, max_length=20)`

Manually copying the textgenrnn_vocab.json, textgenrnn_config.json, and textgenrnn_weights.hdf5 to another folder, Training another model, And then loading a new model from the original saved weights, vocab, config:
`recipes_len20_reload2 = textgenrnn(weights_path='weights/recipes_len20/textgenrnn_weights.hdf5', vocab_path='weights/recipes_len20/textgenrnn_vocab.json', config_path='weights/recipes_len20/textgenrnn_config.json')
`
Then I was able to sample from my saved model:
```
>>>recipes_len20_reload2.generate()
canned with a deveined tomatoes and crushed
salt.  Add the sausage and cook on high speed and sugar to the shrimp.  Seal the casserole in the tomato sauce, pat
each additional mixed
1  water
1  egg
1 tablespoon lemon juice
1 tablespoon curry powder
1/2 teaspoon crumbled cheddar cheese, shredded
1  c
```

It would be nice if .save() did all the copying-to-a-new-folder for me, but at least this seems to work.

**Comment by Oysiyl** [comment]
Make some experiments when got similar error.. I found, that new_model=False work great but new_model=True created broken weights (if weights=1,2 MB. then weights is broken). So if you need train new model, my advice is just do not specify this parameter. In that case I tested few times and library generated each time correct weights (with 1,9 MB.) 
Currently using new_model=True generated broken weights each time for me. 
Hope that can helps anyone!

**Comment by janelleshane** [comment]
Adding this in case it helps people, because it's still possible to end up with a shape error with the workflow above.

textgenrnn_vocab.json and textgenrnn_config.json only update if training is run with "new_model=true"

So, if you initialize a model with my_model = textgenrnn() and then train, the training may still work but the textgenrnn_vocab.json and textgenrnn_config.json won't match your model (so you won't be able to go back to these results later) unless you also run it with "new_model=true".

**Comment by minimaxir** [comment]
Thanks for following up, Janelle!

I admit I haven't polished the transfer learning workflow; I'll take a look at some point.
