### ISSUE TITLE
error when train_on_texts instead of train_from_largetext_file: AttributeError: 'numpy.ndarray' object has no attribute 'lower'

### ISSUE THREAD

**Issue by nylki** [minimaxir/textgenrnn#57]
Hi,
I tried to train your example at https://github.com/minimaxir/textgenrnn/blob/master/docs/textgenrnn-demo.ipynb

my code looks like: 
```py
from textgenrnn import textgenrnn

textgen = textgenrnn()
textgen.reset()
texts = ['Never gonna give you up, never gonna let you down',
        'Never gonna run around and desert you',
        'Never gonna make you cry, never gonna say goodbye',
        'Never gonna tell a lie and hurt you']


textgen.train_on_texts(texts, num_epochs=2,  gen_epochs=2)
```

I get the following output:

```
Using TensorFlow backend.
2018-08-01 15:40:15.286776: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-08-01 15:40:15.356998: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-01 15:40:15.357329: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 7.61GiB
2018-08-01 15:40:15.357343: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2018-08-01 15:40:17.171291: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-01 15:40:17.171337: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 
2018-08-01 15:40:17.171348: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N 
2018-08-01 15:40:17.171563: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7343 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
Training on 174 character sequences.
Epoch 1/2
Traceback (most recent call last):
  File "test2.py", line 11, in <module>
    textgen.train_on_texts(texts, num_epochs=2,  gen_epochs=2)
  File "/home/tom/programming/tensorflow/venv/lib/python3.6/site-packages/textgenrnn/textgenrnn.py", line 194, in train_on_texts
    validation_steps=val_steps
  File "/home/tom/programming/tensorflow/venv/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/tom/programming/tensorflow/venv/lib/python3.6/site-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/tom/programming/tensorflow/venv/lib/python3.6/site-packages/keras/engine/training_generator.py", line 177, in fit_generator
    generator_output = next(output_generator)
  File "/home/tom/programming/tensorflow/venv/lib/python3.6/site-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/home/tom/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/tom/programming/tensorflow/venv/lib/python3.6/site-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "/home/tom/programming/tensorflow/venv/lib/python3.6/site-packages/textgenrnn/model_training.py", line 49, in generate_sequences_from_texts
    x = process_sequence([x], textgenrnn, new_tokenizer)
  File "/home/tom/programming/tensorflow/venv/lib/python3.6/site-packages/textgenrnn/model_training.py", line 79, in process_sequence
    X = new_tokenizer.texts_to_sequences(X)
  File "/home/tom/programming/tensorflow/venv/lib/python3.6/site-packages/keras_preprocessing/text.py", line 274, in texts_to_sequences
    return list(self.texts_to_sequences_generator(texts))
  File "/home/tom/programming/tensorflow/venv/lib/python3.6/site-packages/keras_preprocessing/text.py", line 299, in texts_to_sequences_generator
    text = text.lower()
AttributeError: 'numpy.ndarray' object has no attribute 'lower'
```

**The following does work though** and I get the training step outputs:
```.py
from textgenrnn import textgenrnn
textgen = textgenrnn()
textgen.reset()

train_function = textgen.train_from_largetext_file

train_function(
    file_path='somevalidpath',
    new_model=True,)
```

It seem like its an issue only with training from list of strings directly instead of loading from file.

PS: I am in a python virtual environment with tensorflow-gpu installed on latest Ubuntu 18.

**Comment by nylki** [comment]
Update:
The same error also happens when doing `word_level=True` with `train_from_largetext_file` for me.

**Comment by hay** [comment]
This seems to be an error since version 1.1, with 1.0 i've got no problems running the code i posted above.

**Comment by halesyy** [comment]
I'm getting the same error right now, doing nothing wrong it seems :P

**Comment by halesyy** [comment]
Starting to get it on train_from_largetext_file now, how do I revert back to it?

**Comment by minimaxir** [comment]
Looking into this.

**Comment by minimaxir** [comment]
Issue confirmed. (looks like something changed with a Keras update)

I should be able to work around it.

**Comment by minimaxir** [comment]
`v1.3.2` should fix the issue, it did not reoccur in my testing.

Let me know if everything's OK.

**Comment by mcwatera** [comment]
Hello!  I would really, really like to use this package!  I currently have Python 3.6.8 installed, 

I get this error when pip3 installing textgenrnn:

`ERROR: Package 'PyYAML' requires a different Python: 3.4.10 not in '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*'`

I was wondering if you could help me figure this out, as it makes it very difficult to install textgenrnn and avoid this problem.
